version: '3.9'
services:
  nginx:
    restart: always
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/api/web/pokemon/staticfiles
  web:
    restart: always
    build:
          context: .
          dockerfile: ./deploy/Dockerfile.prod
    command: gunicorn pokemon.django_core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/api/web/pokemon/staticfiles
    expose:
      - 8000
    env_file:
      - ./deploy/.env.prod
    depends_on:
      - db
  db:
    restart: always
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
volumes:
  postgres_data:
  static_volume: