# Generated by Django 3.1.7 on 2021-03-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='id',
        ),
        migrations.AlterField(
            model_name='courier',
            name='courier_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
