# Generated by Django 3.1.7 on 2021-03-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20210308_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='courier',
            new_name='courier_id',
        ),
    ]
