# Generated by Django 3.1.7 on 2021-03-08 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20210308_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='courier_id',
        ),
    ]
