# Generated by Django 3.1.7 on 2021-03-09 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_remove_order_courier_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='article.courier'),
        ),
    ]
