# Generated by Django 3.1.7 on 2021-03-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_order_courier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier_id',
            field=models.IntegerField(default=None),
        ),
    ]
