# Generated by Django 3.1.7 on 2021-03-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20210309_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
