# Generated by Django 3.1.7 on 2021-03-09 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20210309_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='article.courier'),
        ),
    ]
