# Generated by Django 3.1.7 on 2021-10-04 15:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('pokemons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), null=True, size=None)),
            ],
        ),
    ]
