# Generated by Django 3.1.7 on 2021-03-29 16:50

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('courier_type', models.CharField(choices=[('foot', 'foot'), ('bike', 'bike'), ('car', 'car')], max_length=128)),
                ('regions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('working_hours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), null=True, size=None)),
                ('rating', models.FloatField(default=0)),
                ('earnings', models.IntegerField(default=0)),
                ('last_order', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('weight', models.FloatField()),
                ('region', models.IntegerField()),
                ('delivery_hours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), size=None)),
                ('finish_time', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CouriersAndOrders',
            fields=[
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sweets.order')),
                ('completed', models.BooleanField(default=False)),
                ('assign_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('courier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweets.courier')),
            ],
        ),
    ]
